name: 🐛 Bug report
description: You found a bug!
title: '🐛 '
labels: ["🐛 Bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 **Thank you for contributing!**
  - type: markdown
    attributes:
      value: |
        Before submitting a new issue please check the [existing issues](https://github.com/IntersectMBO/council-toolkit-app/issues) to avoid duplication.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: What part of the toolkit does this bug affect?
      options:
        - Transaction inspection
        - Rationale metadata inspection
        - On-chain data viewing
        - Top level - all areas
        - Not sure
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please give the context to what you were trying to achieve
      placeholder: |
        I was trying to X and the following happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Explain the steps to reproduce
      placeholder: |
          1. Connect wallet
          2. Navigate to the dashboard
          3. Click on "Register as DRep"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description:  A description of the erroneous outcome
      placeholder: |
        A error came up on the screen stating...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A description of what you expect to happen instead
      placeholder: |
        The DRep registration transaction was sent and I was registered
    validations:
      required: true