name: Build, test and lint app

on:
  push:
    branches:
      - '**'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Run linter
        run: npm run lint
        working-directory: ./src

      - name: Run tests
        run: npm run test
        working-directory: ./src

      - name: Build application
        run: npm run build
        working-directory: ./src